config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recipes do
    resources :ingredients
    resources :steps
    resources :reviews
  end
  root 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  validates :name, :measurement_qty, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  has_many :steps, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, :category, presence: true

  scope :three_most_recent, -> {order(created_at: :desc).limit(3)}

  def self.search(search)
    Recipe.where("name ILIKE ? or category ILIKE ?", "%#{search}%", "%#{search}%")
  end
  # if you write this as scope
  # scope :search, -> (search) {where("name ILIKE ? or category ILIKE ?", "%#{search}%", "%#{search}%")}
  
  # to get record from only one column
   #Recipe.where("name ILIKE ?", "%#{search}%")
  # to get record from only one column(the other way)
   # Recipe.where('name ILIKE :search OR category ILIKE :search', search: "%#{search}%")
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :recipe
  validates :star, :comment, presence: true
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.new(recipe_id: params[:recipe_id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.new(ingredients_params)
    if @ingredient.save
      redirect_to recipe_path(@recipe), notice: "Ingredient is successfully added!"
    else
      render 'new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.find(params[:id])
    if  @ingredient.update(ingredients_params)
      redirect_to recipe_path(@recipe), notice: "Ingredient is successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.find(params[:id])
    @ingredient.destroy
    redirect_to recipe_path(@recipe), notice: "Ingredient is successfully deleted!"
  end

  private
    def ingredients_params
      params.require(:ingredient).permit(:name, :measurement_unit, :measurement_qty, :recipe_id)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    if(params[:search])
      @searched_recipes = Recipe.search(params[:search])
    elsif (params[:sort] == "atoz")
      @recipes = Recipe.all.order(Arel.sql('lower(name)'))
      @most_recent_recipes = Recipe.three_most_recent
    else
      @recipes = Recipe.all.order(created_at: 'desc')
      @most_recent_recipes = Recipe.three_most_recent
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path, notice: "Recipe was successfully created!"      
    else
      render 'new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    if  @recipe.update(recipe_params)
      redirect_to recipes_path
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  private
    def recipe_params
      params.require(:recipe).permit(:name, :category)
    end
    
    def search_params
      params.require(:recipe).permit(:name, :category, :search)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @review = Review.new(recipe_id: params[:recipe_id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @review = Review.new(review_params)
    if @review.save
      redirect_to recipe_path(@recipe), notice: "Review is successfully added!"
    else
      render 'new'
    end
  end

  private
    def review_params
      params.require(:review).permit(:star, :comment, :recipe_id)
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @step = Step.new(recipe_id: params[:recipe_id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @step = Step.new(step_params)
    if @step.save
      redirect_to recipe_path(@recipe), notice: "Step is successfully added!"
    else
      render 'new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @step = Step.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @step = Step.find(params[:id])
    if @step.update(step_params)
      redirect_to recipe_path(@recipe), notice: "Step is successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @step = Step.find(params[:id])
    if @step.destroy
      redirect_to recipe_path(@recipe), notice: "Step is successfully deleted!"
    end
  end

  private
    def step_params
      params.require(:step).permit(:index, :description, :recipe_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for [@recipe, @ingredient] do |f| %>
  <p>
    <%= f.label :recipe_id %>
    <%= f.select :recipe_id, Recipe.order(:name).pluck(:name, :id), include_blank: true %>
      <% if @ingredient.errors.messages[:recipe_id].any? %>
        <span class="error"><%= @ingredient.errors.messages[:recipe_id][0]%></span>
      <% end %>
  </p>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Ingredient name' %>
      <% if @ingredient.errors.messages[:name].any? %>
        <span class="error"><%= @ingredient.errors.messages[:name][0]%></span>
      <% end %>
  </p>
  <p>
    <%= f.label :measurement_qty %>
    <%= f.text_field :measurement_qty, placeholder: '1' %>
      <% if @ingredient.errors.messages[:measurement_qty].any? %>
        <span class="error"><%= @ingredient.errors.messages[:measurement_qty][0]%></span>
      <% end %>
  </p>
  <p>
    <%= f.select :measurement_unit, [["", ""],["cup", "cup"], ["tea spoon", "tea spoon"], ["table spoon", "table spoon"]] %>
      <% if @ingredient.errors.messages[:measurement_unit].any? %>
        <span class="error"><%= @ingredient.errors.messages[:measurement_unit][0] %></span>
      <% end %>
  </p>

  <p><%= f.submit%></p>
<% end %>

app/views/ingredients/edit.html.erb
<h2>Edit ingredient of <%= @recipe.name %></h2>
<%= render "form" %>

app/views/ingredients/new.html.erb
<h2>Add new ingredients to <%= @recipe.name %> </h2>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyReciperails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
       <%= msg %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'enter name' %>
      <% if @recipe.errors.messages[:name].any? %>
        <span class="error"><%= @recipe.errors.messages[:name][0]%></span>
      <% end %>
  </p>
  <p>
     <%= f.label :category %>
      <%= f.text_field :category, placeholder: 'enter category' %>
        <% if @recipe.errors.messages[:category].any? %>
          <span class="error"><%= @recipe.errors.messages[:category][0]%></span>
        <% end %>
  </p>
  <p><%= f.submit%></p>
<% end %>

app/views/recipes/edit.html.erb
<h2>Edit Recipe of <%= @recipe.name %></h2>
<%= render "form" %>

app/views/recipes/index.html.erb
<h4>Search by Recipes</h4>
  <%= form_with url: recipes_path, method: :get, local: true do  |f| %>
    <div class="field">
      <%= f.text_field :search %>
      <span class="actions">
        <%= f.submit "Search" %>
      </span>
    </div>
  <% end %>

<h2>Recipes</h2>
<ul>
  <% if @searched_recipes %>
    <% @searched_recipes.each do |recipe| %>
      <li>
        <%= recipe.name %>
        <%= link_to '[Show]', recipe_path(recipe) %>
        <%= link_to '[Edit]', edit_recipe_path(recipe) %>
        <%= link_to '[Delete]', recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?'}  %>
      </li>
    <% end%>
  <% else %>
    <% @recipes.each do |recipe| %>
      <li>
        <%= recipe.name %>
        <% if @most_recent_recipes.include?(recipe) %> 
          <span class="text-primary">  New!!! </span>
        <% end %>  
        <%= link_to '[Show]', recipe_path(recipe) %>
        <%= link_to '[Edit]', edit_recipe_path(recipe) %>
        <%= link_to '[Delete]', recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?'}  %>
      </li>
    <% end%>
  <% end%>
</ul>

<p><%= link_to '[Add a new recipe]', new_recipe_path  %></p>
<p><%= link_to '[Sort by alphabetically]', recipes_path(sort: "atoz") %></p>

app/views/recipes/new.html.erb
<h2>New Recipe</h2>
<%= render "form" %>

app/views/recipes/show.html.erb
<h2>How to make <%= @recipe.name %></h2>
  <h3>Category: <%= @recipe.category %></h3>
    <% if @recipe.ingredients.any? %>
      <h4>Ingredients:</h4>
        <ul>
          <% @recipe.ingredients.each do |ingredient| %>
            <li>
              <p>
                <%= ingredient.name %> : <%= ingredient.measurement_qty %> <%= ingredient.measurement_unit %>  
                <%= link_to '[Edit ingredient]', edit_recipe_ingredient_path(@recipe, ingredient) %>
                <%= link_to '[Delete ingredient]', recipe_ingredient_path(@recipe, ingredient), method: :delete, data: { confirm: 'Are you sure?'} %>
              </p>
            </li>
          <% end%>
        </ul>
        <p><%= link_to '[Add ingredients]', new_recipe_ingredient_path(@recipe) %></p>
    <% else %>
    <p><%= link_to '[Add ingredients]', new_recipe_ingredient_path(@recipe) %></p>
    <% end%>

    <% if @recipe.steps.any? %>
      <h4>Steps:</h4>
      <% @recipe.steps.order(:index).each do |step| %>
        <p>
          <%= step.index %>: <%= step.description%> <%= link_to '[Edit step]', edit_recipe_step_path(@recipe, step) %> <%= link_to '[Delete step]', recipe_step_path(@recipe, step), method: :delete, data: { confirm: 'Are you sure?'} %>
        </p>
      <% end %>
      <p><%= link_to '[Add steps]', new_recipe_step_path(@recipe) %></p>
    <% else%>
      <p><%= link_to '[Add steps]', new_recipe_step_path(@recipe) %></p>
    <% end%>
    
  <h4>Reviews (<%= @recipe.reviews.size %>)</h4>
    <p><%= link_to '[Add reviews]', new_recipe_review_path(@recipe) %></p>
      <% if @recipe.reviews.any? %>
        <% @recipe.reviews.each do |review| %>
          <p>
            <%= review.created_at.to_date %>
            <% if review.star? %>
              <% review.star.times do %>
                <span>⭐</span>
              <% end %>
            <% end %>
          </p>
          <p><%= review.comment%></p>
        <% end %>
    <% end %>
  


  <div>
    <%= link_to "[Back]", recipes_path %>
  </div>

app/views/reviews/_form.html.erb
<%= form_with(model: @review, url:[@recipe, @review], local: true) do |f| %>
  <p>
    <%= f.label :recipe_id %>
    <%= f.select :recipe_id, Recipe.order(:name).pluck(:name, :id), include_blank: true %>
      <% if @review.errors.any? %>
        <span class="error"><%= @review.errors.full_messages%></span>
      <% end %>
  </p>

  <div class="form-check form-check-inline">
    <%= f.radio_button :star, :class => "form-check-input"%>
    <%= f.label :star, 1 , class: "form-check-label" %>
  </div>
  <div class="form-check form-check-inline">
    <%= f.radio_button :star, 2, :class => "form-check-input"%>
    <%= f.label :star, 2, class: "form-check-label" %>
  </div>
  <div class="form-check form-check-inline">
    <%= f.radio_button :star, 3, :class => "form-check-input"%>
    <%= f.label :star, 3, class: "form-check-label" %>
  </div>
  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> 

app/views/reviews/new.html.erb
<h2>Add review</h2>

<%= render "form" %>

app/views/steps/_form.html.erb
<%= form_with(model: @step, url: [@recipe, @step], local: true) do |f| %>
  <p>
    <%= f.label :recipe_id %>
    <%= f.select :recipe_id, Recipe.order(:name).pluck(:name, :id), include_blank: true %>
      <% if @step.errors.messages[:recipe_id].any? %>
        <span class="error"><%= @step.errors.messages[:recipe_id][0]%></span>
      <% end %>
  </p>

  <div class="field">
    <%= f.label :index %>
    <%= f.text_field :index %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> 

app/views/steps/edit.html.erb
<h2>Edit step <%= @step.index%></h2>

<%= render "form" %>

app/views/steps/new.html.erb
<h2>Create steps for <%= @recipe.name %></h2>

<%= render "form" %>